mysql:
  host: localhost
  user: root
  pass: pass
  port: 3306
  db: Man10Farm





farm:

  threadroop: 30

  No1:
    seed:
    crop:
    othercrops:
      - asdmfamn:1:4:10
    cropblock:
    canb:
    growc:
    ll:
    cropbreakitem:
